- hosts: all
  vars:
    users:
      - batman
      - superman
      - wonderwoman
    group: justice-league

  tasks:
    - name: Create group
      group:
        name: "{{ group }}"
        state: present

    - name: Create user opertor1
      user:
        name: "{{ item }}"
        shell: /bin/bash
        state: present
      with_items: "{{ users }}"
   
    - name: Add authorized keys
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '../vagrant-lab/id_ed25519.pub') }}"
      with_items: "{{ users }}"


