- hosts: all
  vars:
    users:
      - username: batman
        comment: "Batman user"
        shell: "/bin/bash"
      - username: superman
        comment: "Superman user"
        shell: "/bin/false"
      - username: wonderwoman
        shell: "/bin/sh"
        comment: "Wonderwoman user"
    group: justice-league

  tasks:
    - name: Create group
      group:
        name: "{{ group }}"
        state: present

    - name: Create user opertor1
      user:
        name: "{{ item.username }}"
        shell: "{{ item.shell }}"
        comment: "{{ item.comment }}"
        state: present
      with_items: "{{ users }}"
   
    - name: Add authorized keys
      authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ lookup('file', '../../vagrant-lab/id_ed25519.pub') }}"
      with_items: "{{ users }}"


