- hosts: all 
  roles:
    - { role: update }
    - { role: secure-machine }
    - { role: create-users }

- import_playbook: install_apache.yaml
  when: ansible_os_family == "Debian"
    
- import_playbook: install_mysql.yaml
  when: ansible_os_family == "RedHat"
  tags: installmysql

