---

- name: Install apache and other required packages
  apt:
    name: "{{ apache_packages }}"
    state: present

- name: Restart and enable apache
  systemd:
    name: apache2
    state: restarted
    enabled: yes
